# CloudKit configuration (v6, 2025-09-26)
# 本ファイルは現在の実装/ログに整合する「実動仕様」です。
# 以前の cloudkit_configuration.yaml(v5) からの主な変更点:
# - ルートレコード名を Room → ChatSession に統一
# - Message に timestamp/attachment を持つ実装に合わせて定義
# - parent(親レコード)参照は使用しない（ゾーン＝ルームの単位分離で簡素化）
# - DB/Zone サブスクは CKSyncEngine 前提で DatabaseSubscription のみ
# - 必須インデックス（recordName=Queryable 等）を明示

schema:
  version: 6
  notes: >
    1ルーム=1共有ゾーン（zoneName=room_*）で完全分離。親子レコードの parent は使用しない。
    時系列は Message.timestamp（ユーザーフィールド）で並び替え、システム creationDate も併用可能。

databases:
  private:
    # 既定（__defaultOwner__/Default Zone）を利用
    default_zone:
      record_types:
        - name: MyProfilePrivate
          fields:
            - { name: userId,       type: String, required: true }
            - { name: displayName,  type: String, required: false }
            - { name: avatarAsset,  type: Asset,  required: false }
            - { name: faceTimeID,   type: String, required: false }
          indexes:
            - { fields: [userId], queryable: true }

  shared:
    zones:
      - pattern: "room_*"
        record_types:
          # ルームのルート（レコード名=ゾーン名）
          - name: ChatSession
            fields:
              - { name: roomID,         type: String, required: true }
              - { name: ownerID,        type: String, required: true }
              - { name: createdAt,      type: Date,   required: true }
              - { name: name,           type: String, required: false }
              - { name: shareURL,       type: String, required: false }
              - { name: roomImageAsset, type: Asset,  required: false }
              - { name: roomImageShape, type: Int64,  required: false }
            indexes:
              - { fields: [recordName], queryable: true }
              - { fields: [roomID],     queryable: true }

          - name: RoomMember
            fields:
              - { name: userId,      type: String, required: true }
              - { name: displayName, type: String, required: false }
              - { name: avatarAsset, type: Asset,  required: false }
            indexes:
              - { fields: [recordName],   queryable: true }
              - { fields: [userId],       queryable: true }
              - { fields: [creationDate], order: desc, queryable: true }

          - name: Message
            fields:
              - { name: roomID,    type: String, required: true }
              - { name: senderID,  type: String, required: true }
              - { name: text,      type: String, required: false }
              - { name: timestamp, type: Date,   required: true }
              - { name: attachment,type: Asset,  required: false } # 実装は Message 内に CKAsset を保持
            indexes:
              - { fields: [recordName], queryable: true }
              - { fields: [roomID],     queryable: true }
              - { fields: [timestamp],  order: desc, queryable: true }

          # オプション: 大容量/分離運用したい場合のみ使用（現実装は Message.attachment を優先）
          - name: MessageAttachment
            fields:
              - { name: messageRef, type: Reference(Message), required: true }
              - { name: asset,      type: Asset,              required: true }
              - { name: type,       type: String,             required: false } # "image" | "video" など
            indexes:
              - { fields: [recordName], queryable: true }
              - { fields: [messageRef], queryable: true }

          - name: Reaction
            fields:
              - { name: messageRef, type: Reference(Message),   required: true }
              - { name: memberRef,  type: Reference(RoomMember),required: true }
              - { name: emoji,      type: String,               required: true }
            indexes:
              - { fields: [recordName],   queryable: true }
              - { fields: [messageRef],   queryable: true }
              - { fields: [creationDate], order: desc, queryable: true }

          - name: RTCSignal
            fields:
              - { name: fromMemberRef, type: Reference(RoomMember), required: true }
              - { name: toMemberRef,   type: Reference(RoomMember), required: true }
              - { name: callId,        type: String,                required: true }
              - { name: type,          type: String,                required: true, enum: [offer, answer, ice] }
              - { name: payload,       type: String,                required: true }
              - { name: consumed,      type: Bool,                  required: true,  default: false }
              - { name: ttlSeconds,    type: Int64,                 required: false }
            indexes:
              - { fields: [recordName],  queryable: true }
              - { fields: [toMemberRef], queryable: true }
              - { fields: [callId],      queryable: true }
              - { fields: [consumed],    queryable: true }
              - { fields: [creationDate],order: desc, queryable: true }

subscriptions:
  # CKSyncEngine（iOS 17+）前提。DatabaseSubscription のみで差分駆動。
  - name: private_db_changes
    scope: private
    type: DatabaseSubscription
    notificationInfo:
      shouldSendContentAvailable: true
  - name: shared_db_changes
    scope: shared
    type: DatabaseSubscription
    notificationInfo:
      shouldSendContentAvailable: true

ops_notes:
  - "共有ゾーン（room_*）は Zone Details で 'Zone wide sharing is enabled' を ON"
  - "各 Record Type で system field 'recordName' を Queryable に追加（recordName未インデックスで Consoleクエリが失敗）"
  - "Message 並びは timestamp 降順（Sortable index）"
  - "RTCSignal は toMemberRef / callId にインデックス（P2P適用高速化）"
  - "大容量添付を厳密分離したい場合は MessageAttachment を使用（現実装は Message.attachment を優先）"

